table DimPayer
	lineageTag: ee5cf427-b1db-43be-8576-8b64547c5393

	column PayerKey
		dataType: int64
		isHidden
		lineageTag: cf6d9e81-3592-42e4-a2c3-586480e85a1d
		summarizeBy: none
		sourceColumn: PayerKey

		annotation SummarizationSetBy = Automatic

	column PayerName
		dataType: string
		lineageTag: 5749fbfa-bb80-4ee2-b924-6b67f6686058
		summarizeBy: none
		sourceColumn: PayerName

		annotation SummarizationSetBy = Automatic

	column LOB
		dataType: string
		lineageTag: bc311ccf-9906-416f-aa26-c39ceee8415e
		summarizeBy: none
		sourceColumn: LOB

		annotation SummarizationSetBy = Automatic

	partition DimPayer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\\malik\\power bi traning\\powerbi-accelerator\\cog-to-bi-asgnmt\\day-6\\data\\DimPayer.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"PayerKey", Int64.Type}, {"PayerName", type text}, {"LOB", type text}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

