table FactClaims
	lineageTag: 3b2fa62b-1945-4e37-b5e5-f9985d859dad

	column ClaimID
		dataType: string
		lineageTag: 261647cd-9cc7-403a-8eb6-3a8b690480d5
		summarizeBy: none
		sourceColumn: ClaimID

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		isHidden
		lineageTag: 17d50d7e-f3c0-4ce6-85db-ff3d93b99fe0
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column MemberKey
		dataType: int64
		isHidden
		lineageTag: 64d617be-f0ff-4bf5-b8ea-4e7ac15e3f69
		summarizeBy: none
		sourceColumn: MemberKey

		annotation SummarizationSetBy = Automatic

	column ProviderKey
		dataType: int64
		isHidden
		lineageTag: 7031fc8f-5727-460e-89b9-b36ec7eb89b6
		summarizeBy: none
		sourceColumn: ProviderKey

		annotation SummarizationSetBy = Automatic

	column PayerKey
		dataType: int64
		isHidden
		lineageTag: 37c310fb-a2e2-46a5-9cf3-2691e89dac57
		summarizeBy: none
		sourceColumn: PayerKey

		annotation SummarizationSetBy = Automatic

	column ClaimCount
		dataType: int64
		isHidden
		lineageTag: c2c0a57c-6826-492e-838b-99f6579719c6
		summarizeBy: sum
		sourceColumn: ClaimCount

		annotation SummarizationSetBy = Automatic

	column BilledAmount
		dataType: double
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: e5583774-7638-4423-b368-12ec25d3b57a
		summarizeBy: sum
		sourceColumn: BilledAmount

		annotation SummarizationSetBy = Automatic

	column AllowedAmount
		dataType: double
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: bfaf4d2c-b7c2-4bbe-8548-ae945309ede6
		summarizeBy: sum
		sourceColumn: AllowedAmount

		annotation SummarizationSetBy = Automatic

	column PaidAmount
		dataType: double
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 1a9468bf-a546-47af-8409-255669396336
		summarizeBy: sum
		sourceColumn: PaidAmount

		annotation SummarizationSetBy = Automatic

	column MemberMonths
		dataType: int64
		isHidden
		lineageTag: 9dfa659b-ba28-47bd-b1f2-9dea7fc4cf28
		summarizeBy: sum
		sourceColumn: MemberMonths

		annotation SummarizationSetBy = Automatic

	partition FactClaims = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\\malik\\power bi traning\\powerbi-accelerator\\cog-to-bi-asgnmt\\day-6\\data\\FactClaims.csv"),[Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ClaimID", type text}, {"DateKey", Int64.Type}, {"MemberKey", Int64.Type}, {"ProviderKey", Int64.Type}, {"PayerKey", Int64.Type}, {"ClaimCount", Int64.Type}, {"BilledAmount", type number}, {"AllowedAmount", type number}, {"PaidAmount", type number}, {"MemberMonths", Int64.Type}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

