table FactRevenue
	lineageTag: 3a314520-0599-4361-af80-0b26100b5a9c

	column DateKey
		dataType: int64
		isHidden
		lineageTag: b3b95209-2b7a-45e0-a2f9-b91cf558f37a
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column PayerKey
		dataType: int64
		isHidden
		lineageTag: 5afd9ac2-48c1-4a80-881d-dac6dab8f2ee
		summarizeBy: none
		sourceColumn: PayerKey

		annotation SummarizationSetBy = Automatic

	column RevenueAmount
		dataType: double
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 3ea282ce-2508-420b-96c9-831a0da42294
		summarizeBy: sum
		sourceColumn: RevenueAmount

		annotation SummarizationSetBy = Automatic

	partition FactRevenue = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\\malik\\power bi traning\\powerbi-accelerator\\cog-to-bi-asgnmt\\day-6\\data\\FactRevenue.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DateKey", Int64.Type}, {"PayerKey", Int64.Type}, {"RevenueAmount", type number}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

