table FactClaims
	lineageTag: c1a5c94e-327f-4d2b-b83f-18b428aea5fe

	column ClaimKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 42e94d67-b621-45e2-aaa8-138e008b62cf
		summarizeBy: none
		sourceColumn: ClaimKey

		annotation SummarizationSetBy = Automatic

	column ClaimID
		dataType: string
		lineageTag: ae2359ba-3314-437c-ab4b-1cf5f17e3f3a
		summarizeBy: none
		sourceColumn: ClaimID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 358c83e5-853a-49b8-92fd-d81e9a708df4
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MemberKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f5d869aa-c399-4e90-b3ae-28df9dafceb3
		summarizeBy: none
		sourceColumn: MemberKey

		annotation SummarizationSetBy = Automatic

	column ProviderKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f59cee11-829a-4a6a-9816-56881f4d8987
		summarizeBy: none
		sourceColumn: ProviderKey

		annotation SummarizationSetBy = Automatic

	column PayerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 98029586-a06d-4a5b-997b-910aec6c8f18
		summarizeBy: none
		sourceColumn: PayerKey

		annotation SummarizationSetBy = Automatic

	column ServiceType
		dataType: string
		lineageTag: b5ed75a4-f8ab-49f3-a42e-f56328322c00
		summarizeBy: none
		sourceColumn: ServiceType

		annotation SummarizationSetBy = Automatic

	column ClaimStatus
		dataType: string
		lineageTag: acb6b19b-4038-4abb-bcb8-fe67afe59381
		summarizeBy: none
		sourceColumn: ClaimStatus

		annotation SummarizationSetBy = Automatic

	column AllowedAmount
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a77fe088-f4a4-444e-a1dd-a6b301b467de
		summarizeBy: sum
		sourceColumn: AllowedAmount

		annotation SummarizationSetBy = Automatic

	column PaidAmount
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: da5651a8-a9de-4998-affc-7a5c3f5e891f
		summarizeBy: sum
		sourceColumn: PaidAmount

		annotation SummarizationSetBy = Automatic

	column LengthOfStay
		dataType: int64
		formatString: #,0
		lineageTag: f6a590a3-f5d7-4874-a019-2a701733a989
		summarizeBy: none
		sourceColumn: LengthOfStay

		annotation SummarizationSetBy = Automatic

	column ClaimCost
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: e9d13d45-d046-4feb-bed7-b573692614b0
		summarizeBy: sum
		sourceColumn: ClaimCost

		annotation SummarizationSetBy = Automatic

	column 'LOS Bucket Sort'
		dataType: int64
		isHidden
		lineageTag: e37d8577-fd3a-4432-b11c-b783251bc34f
		summarizeBy: none
		sourceColumn: LOS Bucket Sort

	column 'LOS Bucket'
		dataType: string
		lineageTag: b66b63a9-e1a3-4ab0-a71a-147a1cdc0be9
		summarizeBy: none
		sourceColumn: LOS Bucket
		sortByColumn: 'LOS Bucket Sort'

	partition FactClaims = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "FactClaims.csv"), [Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"ClaimKey", Int64.Type}, {"ClaimID", type text}, {"Date", type date}, {"MemberKey", Int64.Type}, {"ProviderKey", Int64.Type}, {"PayerKey", Int64.Type}, {"ServiceType", type text}, {"ClaimStatus", type text}, {"AllowedAmount", Currency.Type}, {"PaidAmount", Currency.Type}, {"LengthOfStay", Int64.Type}, {"ClaimCost", Currency.Type}}, "en-US"),
				    Trimmed = Table.TransformColumns(Typed, {{"ClaimID", Text.Trim, type text}, {"ServiceType", Text.Trim, type text}, {"ClaimStatus", Text.Trim, type text}}),
				    LOSBucket = Table.AddColumn(Trimmed, "LOS Bucket", each if [LengthOfStay] = 0 then "0 days" else if [LengthOfStay] <= 3 then "1-3 days" else if [LengthOfStay] <= 7 then "4-7 days" else "8+ days", type text),
				    LOSSort = Table.AddColumn(LOSBucket, "LOS Bucket Sort", each if [LengthOfStay] = 0 then 1 else if [LengthOfStay] <= 3 then 2 else if [LengthOfStay] <= 7 then 3 else 4, Int64.Type)
				in
				    LOSSort

	annotation PBI_ResultType = Table

