table DimDate
	lineageTag: b7996293-effb-4316-94f1-8a29a1551105
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: a791543a-339c-4f5c-8079-780fcd48fccf
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DateKey
		dataType: int64
		isHidden
		lineageTag: fb19d8b2-37a6-4898-b495-322c8eda6d9e
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: f5bd3a2f-50e3-48b6-be0f-3e41d0066c80
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthNo
		dataType: int64
		isHidden
		lineageTag: 7b703ea1-954a-498c-a2d2-8311f8e9a2d3
		summarizeBy: none
		sourceColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 5290b03c-f671-4550-8235-ebba982f2ad7
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: ce2ad235-e0f2-430b-9d7e-81eb9ca2c05f
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column YearMonthNo = DimDate[Year] * 100 + DimDate[MonthNo]
		dataType: int64
		isHidden
		lineageTag: 80a82fab-993d-42b6-8159-9beb05df89a4
		summarizeBy: none

	column Year-Month = FORMAT(DimDate[Date], "MMM yyyy")
		dataType: string
		lineageTag: f8b2c307-e756-4230-9cb4-91eeab0329ec
		summarizeBy: none
		sortByColumn: YearMonthNo

	hierarchy Calendar
		lineageTag: ad586699-5e8b-4025-a91e-988b1538fa0f

		level Year
			lineageTag: 71aecf2c-4da8-41c2-8fc2-6a266ec1ed81
			column: Year

		level Quarter
			lineageTag: af1f07d7-c128-4201-88e6-f438c5b4b09e
			column: Quarter

		level Month
			lineageTag: bdb0f22c-1c04-45cb-8ea5-0d1f18bc97a3
			column: Month

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\\malik\\power bi traning\\powerbi-accelerator\\cog-to-bi-asgnmt\\day-6\\data\\DimDate.csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"DateKey", Int64.Type}, {"Year", Int64.Type}, {"MonthNo", Int64.Type}, {"Month", type text}, {"Quarter", type text}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

