/// Cognos query subject DimRegion. The sales region comes only from FactSales.RegionKey.
table DimRegion
	lineageTag: 19e28fef-2a49-45c2-b331-8f873c11db03

	column RegionKey
		dataType: int64
		isHidden
		lineageTag: 994cf836-05b9-4f59-b345-a7a645d33669
		summarizeBy: none
		sourceColumn: RegionKey

	column Region
		dataType: string
		lineageTag: 67f74f7b-ebf1-473f-a12c-372b9de8a5b4
		summarizeBy: none
		sourceColumn: Region

	partition DimRegion = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents(DataFolder & "\DimRegion.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  Typed = Table.TransformColumnTypes(Promoted, {{"RegionKey", Int64.Type}, {"Region", type text}})
				in
				  Typed

