table dim_line_of_business
	lineageTag: 6d221027-29de-4e87-b67b-8d902d69a740

	column lob_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d8a19d87-fea3-45d0-8ac8-6227b3fbd606
		summarizeBy: none
		sourceColumn: lob_key

		annotation SummarizationSetBy = Automatic

	column lob_code
		dataType: string
		lineageTag: 730f0f8e-2ff1-47cc-a0c7-fd273fd2a2ea
		summarizeBy: none
		sourceColumn: lob_code

		annotation SummarizationSetBy = Automatic

	column lob_name
		dataType: string
		lineageTag: 0c6e8e54-94f7-4530-b3af-e3053d46645f
		summarizeBy: none
		sourceColumn: lob_name

		annotation SummarizationSetBy = Automatic

	column lob_desc
		dataType: string
		lineageTag: bce91613-66ae-4539-abe4-dba0adea20d1
		summarizeBy: none
		sourceColumn: lob_desc

		annotation SummarizationSetBy = Automatic

	partition dim_line_of_business = m
		mode: import
		source =
				let
				    Source = fnLoadBySignature("lob_code"),
				    Selected = Table.SelectColumns(Source, {"lob_key", "lob_code", "lob_name", "lob_desc"}, MissingField.UseNull),
				    Typed = Table.TransformColumnTypes(Selected, {{"lob_key", Int64.Type}, {"lob_code", type text}, {"lob_name", type text}, {"lob_desc", type text}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

