/// Calendar. FIX: source date_key is a surrogate (1,2,3...) but the fact uses YYYYMMDD; date_key_int is derived from full_date and is the relationship key.
table dim_date
	lineageTag: 83c26fbc-d49c-41b3-afc5-28bf50eb01cc

	column date_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: df7b41d5-18cc-425c-afb9-3c0faca7eb64
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column full_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 1b29cd8c-c711-4a48-8c4f-bca9f5bd399a
		summarizeBy: none
		sourceColumn: full_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: dafb1597-8d8b-4e0a-b730-05662742c18c
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: c284ca66-4456-41b6-b007-16ec5fe1301d
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column quarter_name
		dataType: string
		lineageTag: f51893ed-6f06-4d0b-a50f-01bd3c83cb15
		summarizeBy: none
		sourceColumn: quarter_name
		sortByColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 26937401-ddc2-4b17-a564-625e8e95044d
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 5b889a2d-ee45-4e7c-9a5d-0f4b95066986
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month

		annotation SummarizationSetBy = Automatic

	column week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 0e2b75da-32b4-4c2e-84b7-cd1c36e4e944
		summarizeBy: none
		sourceColumn: week_of_year

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: cc05664c-f2cb-4f6b-b5b5-d1cd25a63a4c
		summarizeBy: none
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: int64
		formatString: 0
		lineageTag: f20b379f-e9f0-474a-9eb6-7b74a4c4a7a8
		summarizeBy: none
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: 5b64f5d2-d7af-4e2f-9cde-579d32ec218a
		summarizeBy: none
		sourceColumn: day_name
		sortByColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		lineageTag: 8fe1ea06-7e10-4f20-bb54-3086067af54a
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column date_key_int
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ab9e8836-2237-4711-b829-4af6e1b06dea
		summarizeBy: none
		sourceColumn: date_key_int

		annotation SummarizationSetBy = Automatic

	column month_start
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 12d7492c-3142-4bfe-8d61-216784691188
		summarizeBy: none
		sourceColumn: month_start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year_month
		dataType: string
		lineageTag: f25f0db6-6a75-40c2-ba43-46f31bcb89f3
		summarizeBy: none
		sourceColumn: year_month
		sortByColumn: year_month_sort

		annotation SummarizationSetBy = Automatic

	column year_month_sort
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 92deeb48-5e0d-4eb2-96e2-4c16cfe8ff85
		summarizeBy: none
		sourceColumn: year_month_sort

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Source = fnLoadBySignature("full_date"),
				    Selected = Table.SelectColumns(Source, {"date_key", "full_date", "year", "quarter", "quarter_name", "month", "month_name", "week_of_year", "day", "day_of_week", "day_name", "is_weekend"}, MissingField.UseNull),
				    Typed = Table.TransformColumnTypes(Selected, {{"date_key", Int64.Type}, {"full_date", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"quarter_name", type text}, {"month", Int64.Type}, {"month_name", type text}, {"week_of_year", Int64.Type}, {"day", Int64.Type}, {"day_of_week", Int64.Type}, {"day_name", type text}, {"is_weekend", type logical}}, "en-US"),
				    // Keep only full calendar years that have fact data (derived from the fact file, not hard-coded)
				    FactDates = Table.TransformColumnTypes(Table.SelectColumns(fnLoadBySignature("pi_measures_key"), {"date_key"}), {{"date_key", Int64.Type}}),
				    FirstDay = #date(Number.IntegerDivide(List.Min(FactDates[date_key]), 10000), 1, 1),
				    LastDay = #date(Number.IntegerDivide(List.Max(FactDates[date_key]), 10000), 12, 31),
				    InRange = Table.SelectRows(Typed, each [full_date] >= FirstDay and [full_date] <= LastDay),
				    WithKey = Table.AddColumn(InRange, "date_key_int", each Date.Year([full_date]) * 10000 + Date.Month([full_date]) * 100 + Date.Day([full_date]), Int64.Type),
				    WithMonthStart = Table.AddColumn(WithKey, "month_start", each Date.StartOfMonth([full_date]), type date),
				    WithYM = Table.AddColumn(WithMonthStart, "year_month", each Date.ToText([full_date], "MMM yyyy", "en-US"), type text),
				    WithYMSort = Table.AddColumn(WithYM, "year_month_sort", each Date.Year([full_date]) * 100 + Date.Month([full_date]), Int64.Type)
				in
				    WithYMSort

	annotation PBI_ResultType = Table

