/// Employer groups. Loaded from dim_pi_service.csv (file names swapped). Adds a "Not Assigned" member (-1) for null fact keys and an "Unmapped" member for every fact key missing from the dimension.
table dim_employer_group
	lineageTag: 354a8f2c-d17c-4da3-a8d5-3161f207e387

	column employer_group_key
		dataType: int64
		isHidden
		lineageTag: c3d01b0d-e8f5-4ba6-802b-05dbddac6e06
		summarizeBy: none
		sourceColumn: employer_group_key

	column employer_group_code
		dataType: string
		lineageTag: 24f51032-83f3-449b-814f-ef01aa20ed28
		summarizeBy: none
		sourceColumn: employer_group_code

	column employer_group_name
		dataType: string
		lineageTag: 18466316-12b9-4067-b564-dcd02541f17d
		summarizeBy: none
		sourceColumn: employer_group_name

	column eg_client_key
		dataType: int64
		isHidden
		lineageTag: 96e57bfa-34e2-43fc-8ece-2d7be599135a
		summarizeBy: none
		sourceColumn: eg_client_key

	column primary_lob_code
		dataType: string
		lineageTag: c7eb02e1-4c9e-481a-bae7-9f36c8cad502
		summarizeBy: none
		sourceColumn: primary_lob_code

	column primary_funding_type_code
		dataType: string
		lineageTag: ff35ac4e-8448-4f8a-a093-524083083088
		summarizeBy: none
		sourceColumn: primary_funding_type_code

	column mapping_status
		dataType: string
		lineageTag: dd8e9bfa-40e9-4e99-8a13-79a3fabb3323
		summarizeBy: none
		sourceColumn: mapping_status

	partition dim_employer_group = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_pi_service.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Selected = Table.SelectColumns(Promoted, {"employer_group_key", "employer_group_code", "employer_group_name", "client_key", "primary_lob_code", "primary_funding_type_code"}),
				    Renamed = Table.RenameColumns(Selected, {{"client_key", "eg_client_key"}}),
				    Typed = Table.TransformColumnTypes(Renamed, {{"employer_group_key", Int64.Type}, {"employer_group_code", type text}, {"employer_group_name", type text}, {"eg_client_key", Int64.Type}, {"primary_lob_code", type text}, {"primary_funding_type_code", type text}}, "en-US"),
				    Mapped = Table.AddColumn(Typed, "mapping_status", each "Mapped", type text),
				    FactRaw = Table.PromoteHeaders(Csv.Document(File.Contents(DataFolder & "fact_pi_measures.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), [PromoteAllScalars=true]),
				    FactKeys = List.Distinct(List.Transform(FactRaw[employer_group_key], each if _ = "null" or _ = "" then -1 else Number.From(_))),
				    MissingKeys = List.Sort(List.Difference(FactKeys, Typed[employer_group_key])),
				    MissingRows = Table.FromRecords(List.Transform(MissingKeys, each [
				        employer_group_key = _,
				        employer_group_code = if _ = -1 then "EG-NONE" else "EG-UNMAPPED-" & Text.From(_),
				        employer_group_name = if _ = -1 then "Not Assigned" else "Unmapped Group (key " & Text.From(_) & ")",
				        eg_client_key = null, primary_lob_code = null, primary_funding_type_code = null,
				        mapping_status = if _ = -1 then "Not Assigned (null key)" else "Orphan key (missing in dimension)"
				    ]), type table [employer_group_key = Int64.Type, employer_group_code = text, employer_group_name = text, eg_client_key = nullable Int64.Type, primary_lob_code = nullable text, primary_funding_type_code = nullable text, mapping_status = text]),
				    Combined = Table.Combine({Mapped, MissingRows})
				in
				    Combined

