/// Payer clients (SCD2 - Legacy Regional Plan expired 2023-12-31 and has no fact rows).
table dim_client
	lineageTag: b8103efe-de3f-4c71-91e4-8f797174236e

	column client_key
		dataType: int64
		isHidden
		lineageTag: d2430ea8-20d6-41d8-a9ad-91e090f5e96a
		summarizeBy: none
		sourceColumn: client_key

	column client_code
		dataType: string
		lineageTag: c6b63c02-5805-4d63-a2b4-e605c7fe1df4
		summarizeBy: none
		sourceColumn: client_code

	column client_name
		dataType: string
		lineageTag: 60eb6605-e609-4ee6-8031-f4ac7032928f
		summarizeBy: none
		sourceColumn: client_name

	column client_category
		dataType: string
		lineageTag: 83f01deb-c2cb-4929-804b-f719213ebcbc
		summarizeBy: none
		sourceColumn: client_category

	column is_current
		dataType: boolean
		lineageTag: 33f115c1-c359-484a-a42b-476d9ad6cd92
		summarizeBy: none
		sourceColumn: is_current

	partition dim_client = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_client.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Selected = Table.SelectColumns(Promoted, {"client_key", "client_code", "client_name", "client_category", "is_current"}),
				    NullFixed = Table.ReplaceValue(Selected, "null", null, Replacer.ReplaceValue, Table.ColumnNames(Selected)),
				    Typed = Table.TransformColumnTypes(NullFixed, {{"client_key", Int64.Type}, {"client_code", type text}, {"client_name", type text}, {"client_category", type text}, {"is_current", type logical}}, "en-US")
				in
				    Typed

