/// Line of business: Commercial, Medicare, Medicaid, Exchange/ACA.
table dim_line_of_business
	lineageTag: 69908726-86db-476b-ae7e-c9ceae2dd10f

	column lob_key
		dataType: int64
		isHidden
		lineageTag: d69f442f-8786-4a92-b143-e906078da5ec
		summarizeBy: none
		sourceColumn: lob_key

	column lob_code
		dataType: string
		lineageTag: a6e02b41-dd79-4277-9936-586e69307028
		summarizeBy: none
		sourceColumn: lob_code

	column lob_name
		dataType: string
		lineageTag: f45611ce-396a-403b-8fa7-bc93481ab086
		summarizeBy: none
		sourceColumn: lob_name

	column lob_desc
		dataType: string
		lineageTag: 268123b7-3e0e-47d8-b3b8-7e939d42e1a6
		summarizeBy: none
		sourceColumn: lob_desc

	partition dim_line_of_business = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_line_of_business.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Selected = Table.SelectColumns(Promoted, {"lob_key", "lob_code", "lob_name", "lob_desc"}),
				    NullFixed = Table.ReplaceValue(Selected, "null", null, Replacer.ReplaceValue, Table.ColumnNames(Selected)),
				    Typed = Table.TransformColumnTypes(NullFixed, {{"lob_key", Int64.Type}, {"lob_code", type text}, {"lob_name", type text}, {"lob_desc", type text}}, "en-US")
				in
				    Typed

