/// Providers (SCD2 - Sunrise Rehabilitation re-registered as LLC on 2024-04-01). Drill-through key: provider_name.
table dim_provider
	lineageTag: cacabfa9-2449-4e5c-8d40-119d239d2173

	column provider_key
		dataType: int64
		isHidden
		lineageTag: 10a26e0f-7602-4e7c-a074-ba825c70e39a
		summarizeBy: none
		sourceColumn: provider_key

	column provider_tin
		dataType: string
		lineageTag: f303e0e3-0ebd-4e26-8d64-ac453c320c47
		summarizeBy: none
		sourceColumn: provider_tin

	column provider_npi
		dataType: string
		lineageTag: a00815a5-a8f4-4539-a7b2-a0a2c3c0063e
		summarizeBy: none
		sourceColumn: provider_npi

	column provider_name
		dataType: string
		lineageTag: 96f96bde-2d20-41b0-b827-eb047b783b5e
		summarizeBy: none
		sourceColumn: provider_name

	column provider_type
		dataType: string
		lineageTag: 56ba6c26-95fd-4a3a-bab9-66488e8b2096
		summarizeBy: none
		sourceColumn: provider_type

	column provider_state
		dataType: string
		lineageTag: b1639245-1159-45cb-ad99-445e8e2cc3b7
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: provider_state

	column is_current
		dataType: boolean
		lineageTag: cfcfe8cc-ad35-4ecd-b4a9-7d34752bbfe7
		summarizeBy: none
		sourceColumn: is_current

	partition dim_provider = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_provider.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Selected = Table.SelectColumns(Promoted, {"provider_key", "provider_tin", "provider_npi", "provider_name", "provider_type", "provider_state", "is_current"}),
				    NullFixed = Table.ReplaceValue(Selected, "null", null, Replacer.ReplaceValue, Table.ColumnNames(Selected)),
				    Typed = Table.TransformColumnTypes(NullFixed, {{"provider_key", Int64.Type}, {"provider_tin", type text}, {"provider_npi", type text}, {"provider_name", type text}, {"provider_type", type text}, {"provider_state", type text}, {"is_current", type logical}}, "en-US")
				in
				    Typed

