/// Payment Integrity service catalogue. NOTE: the extract file names are swapped - this table is loaded from dim_employer_group.csv.
table dim_pi_service
	lineageTag: 1a0979ab-a056-4674-ad7f-c1ab162c2b7a

	column pi_service_key
		dataType: int64
		isHidden
		lineageTag: 12148914-4988-4f41-94e9-f06fc41f9a72
		summarizeBy: none
		sourceColumn: pi_service_key

	column pi_service_code
		dataType: string
		lineageTag: a2e3c9ee-86d0-42d1-a4d9-596840e82da6
		summarizeBy: none
		sourceColumn: pi_service_code

	column pi_service_name
		dataType: string
		lineageTag: d1d51a0a-d810-42e9-b4c5-f7799f417e51
		summarizeBy: none
		sourceColumn: pi_service_name

	column pi_service_timing
		dataType: string
		lineageTag: 42ea5e08-473b-4bbc-a03e-c83feccc9b74
		summarizeBy: none
		sourceColumn: pi_service_timing

	column pi_service_desc
		dataType: string
		lineageTag: d8de9c8e-1d45-4860-bff2-0cb569e4a7c2
		summarizeBy: none
		sourceColumn: pi_service_desc

	partition dim_pi_service = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_employer_group.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Selected = Table.SelectColumns(Promoted, {"pi_service_key", "pi_service_code", "pi_service_name", "pi_service_timing", "pi_service_desc"}),
				    NullFixed = Table.ReplaceValue(Selected, "null", null, Replacer.ReplaceValue, Table.ColumnNames(Selected)),
				    Typed = Table.TransformColumnTypes(NullFixed, {{"pi_service_key", Int64.Type}, {"pi_service_code", type text}, {"pi_service_name", type text}, {"pi_service_timing", type text}, {"pi_service_desc", type text}}, "en-US")
				in
				    Typed

