/// Monthly Payment Integrity measures, one row per client/LOB/funding/service/claim type/analytic/provider/employer group/source/month. 248 rows.
table fact_pi_measures
	lineageTag: 74758f3f-357e-4086-9d76-965912023786

	column pi_measures_key
		dataType: int64
		isHidden
		lineageTag: ae5e26a1-a6b9-41af-b800-371cfeec1511
		summarizeBy: none
		sourceColumn: pi_measures_key

	column client_key
		dataType: int64
		isHidden
		lineageTag: 4f6392d1-8bee-4b06-a000-f1b337562016
		summarizeBy: none
		sourceColumn: client_key

	column lob_key
		dataType: int64
		isHidden
		lineageTag: 4e38d608-3cc9-4b83-a4a2-5106b440b582
		summarizeBy: none
		sourceColumn: lob_key

	column funding_type_key
		dataType: int64
		isHidden
		lineageTag: e59b040b-415a-4064-8ac2-80c2ee2da7c9
		summarizeBy: none
		sourceColumn: funding_type_key

	column pi_service_key
		dataType: int64
		isHidden
		lineageTag: c2264a30-a6d2-49ad-a3d0-0f69cc41ff79
		summarizeBy: none
		sourceColumn: pi_service_key

	column claim_type_key
		dataType: int64
		isHidden
		lineageTag: 2a94083b-3154-4283-97f1-b816fd973118
		summarizeBy: none
		sourceColumn: claim_type_key

	column analytic_key
		dataType: int64
		isHidden
		lineageTag: d0bd1bf6-f578-4899-91a0-865bb71dcf24
		summarizeBy: none
		sourceColumn: analytic_key

	column provider_key
		dataType: int64
		isHidden
		lineageTag: 931fc5f5-76cb-4f81-a2b4-af961383868e
		summarizeBy: none
		sourceColumn: provider_key

	column employer_group_key
		dataType: int64
		isHidden
		lineageTag: 6494655f-42b7-4034-9979-fbc2ccc68b67
		summarizeBy: none
		sourceColumn: employer_group_key

	column source_system_key
		dataType: int64
		isHidden
		lineageTag: 3b19937c-e069-4268-aa4e-7576ea9fb54c
		summarizeBy: none
		sourceColumn: source_system_key

	column date_key
		dataType: int64
		isHidden
		lineageTag: 76e6aed6-4592-4805-90ad-88c36aa89656
		summarizeBy: none
		sourceColumn: date_key

	column period_date
		dataType: dateTime
		isHidden
		formatString: dd-mmm-yyyy
		lineageTag: f942f289-7b7a-4df3-a6ed-bfc2e7bffd2c
		summarizeBy: none
		sourceColumn: period_date

		annotation UnderlyingDateTimeDataType = Date

	column total_claims_submitted_amount
		dataType: double
		isHidden
		formatString: #,0
		lineageTag: 5eb573fa-2924-4f9b-8b2c-e6a6989c2108
		summarizeBy: sum
		sourceColumn: total_claims_submitted_amount

	column total_claims_pre_edit_allowed_amount
		dataType: double
		isHidden
		formatString: #,0
		lineageTag: a6752fcc-00d5-4808-919e-1d379b39846c
		summarizeBy: sum
		sourceColumn: total_claims_pre_edit_allowed_amount

	column total_claims_processed_amount
		dataType: double
		isHidden
		formatString: #,0
		lineageTag: 90a83509-708b-4877-99aa-c26c5140bbe2
		summarizeBy: sum
		sourceColumn: total_claims_processed_amount

	column total_billed_amount
		dataType: decimal
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7da0b479-c624-45b1-aa43-b2d46c492e06
		summarizeBy: sum
		sourceColumn: total_billed_amount

	column total_paid_amount
		dataType: decimal
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 4d72fea2-8326-4272-a670-077a05388dbb
		summarizeBy: sum
		sourceColumn: total_paid_amount

	column pre_pay_savings_amount
		dataType: decimal
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 49b1e04c-bb5c-410e-8acf-dace6b8dc312
		summarizeBy: sum
		sourceColumn: pre_pay_savings_amount

	column post_pay_savings_amount
		dataType: decimal
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ace6b29d-7802-4549-99b5-1b7ef0d77628
		summarizeBy: sum
		sourceColumn: post_pay_savings_amount

	column total_savings_amount
		dataType: decimal
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: aa8ce345-5324-45b9-a3ea-2d9af7d52863
		summarizeBy: sum
		sourceColumn: total_savings_amount

	column true_positive_rate_pct
		dataType: double
		isHidden
		formatString: 0.0
		lineageTag: 0b7440b2-59ba-44c7-92ae-50bd93e19060
		summarizeBy: average
		sourceColumn: true_positive_rate_pct

	partition fact_pi_measures = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "fact_pi_measures.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Removed = Table.RemoveColumns(Promoted, {"updated_at"}),
				    // 124 rows have no employer group - point them at the "Not Assigned" member (-1)
				    EgFixed = Table.ReplaceValue(Removed, "null", "-1", Replacer.ReplaceValue, {"employer_group_key"}),
				    Typed = Table.TransformColumnTypes(EgFixed, {
				        {"pi_measures_key", Int64.Type}, {"client_key", Int64.Type}, {"lob_key", Int64.Type}, {"funding_type_key", Int64.Type},
				        {"pi_service_key", Int64.Type}, {"claim_type_key", Int64.Type}, {"analytic_key", Int64.Type}, {"provider_key", Int64.Type},
				        {"employer_group_key", Int64.Type}, {"source_system_key", Int64.Type}, {"date_key", Int64.Type},
				        {"total_claims_submitted_amount", type number}, {"total_claims_pre_edit_allowed_amount", type number}, {"total_claims_processed_amount", type number},
				        {"total_billed_amount", Currency.Type}, {"total_paid_amount", Currency.Type}, {"pre_pay_savings_amount", Currency.Type},
				        {"post_pay_savings_amount", Currency.Type}, {"total_savings_amount", Currency.Type}, {"true_positive_rate_pct", type number}}, "en-US"),
				    // fact date_key is YYYYMMDD but dim_date.date_key is a 1..2557 surrogate - relate on a real date instead
				    AddDate = Table.AddColumn(Typed, "period_date", each #date(Number.IntegerDivide([date_key], 10000), Number.Mod(Number.IntegerDivide([date_key], 100), 100), Number.Mod([date_key], 100)), type date)
				in
				    AddDate

